Fix: Generate inline styles without !important (#149)
milkshakesoftware/PreMailer.Net pull request #260
Opened 2021-05-12 09:04 UTC by r-Larch

This pull request removes `!important` from generated inline styles.

This change makes sense because the intention of `!important` is to overwrite inline styles,
so inline styles with `!important` have no real reason to exist.
And as seen in #149 Outlook considers inline styles with it as invalid and ignores them as a whole.

I thought about making this change configurable, but I don't see a benefit from doing so.

I hope this pull request is welcome.

Best regards

2021-05-12 12:43 UTC, martinnormark requested changes
PRs are always welcome!

As important doesn't make much sense inline, perhaps the wording should imply you are opting in the have it emitted to the result?

Would you mind adding appropriate unit tests for this behavior?

2021-05-12 12:43 UTC, martinnormark commented on PreMailer.Net/PreMailer.Net/CssAttribute.cs
> +				: $"{Style}: {Value}{(Important ? " !important" : string.Empty)}";
```suggestion
		/// <summary>
		/// Generates css styles with or without !important
		/// </summary>
		/// <param name="emitImportant">When set to <c>true</c>, resulting CSS emits the !important flag.</param>
		/// <returns> css styles with or without !important </returns>
		public string ToString(bool emitImportant = false)
		{
			return $"{Style}: {Value}{(Important && emitImportant  ? " !important" : string.Empty)}";

```

2021-05-12 12:43 UTC, martinnormark commented on PreMailer.Net/PreMailer.Net/CssElementStyleResolver.cs
> +				attributeCssList.Add(new AttributeToCss { AttributeName = "style", CssValue = styleClass.ToString(removeImportant: true) });
```suggestion
				attributeCssList.Add(new AttributeToCss { AttributeName = "style", CssValue = styleClass.ToString() });
```

2021-05-12 12:43 UTC, martinnormark commented on PreMailer.Net/PreMailer.Net/CssAttribute.cs
> +			return ToString(removeImportant: false);
```suggestion
			return ToString(emitImportant: false);

```

2021-05-12 12:43 UTC, martinnormark commented on PreMailer.Net/PreMailer.Net/StyleClass.cs
> +			return ToString(removeImportant: false);
```suggestion
			return ToString(emitImportant: false);

```

2021-05-12 12:43 UTC, martinnormark commented on PreMailer.Net/PreMailer.Net/StyleClass.cs
> +			return string.Join(";", Attributes.Values.Select(_ => _.ToString(removeImportant)));
```suggestion
		/// <param name="emitImportant">When set to <c>true</c>, resulting CSS emits the !important flag.</param>
		/// <returns> css styles with or without !important </returns>
		public string ToString(bool emitImportant) {
			return string.Join(";", Attributes.Values.Select(_ => _.ToString(emitImportant)));

```

2021-05-15 10:28 UTC, r-Larch commented
Applied suggestions from code review and added unit tests 😉

2021-05-15 12:17 UTC, martinnormark approved these changes
💪🏻

2021-05-15 12:17 UTC, merged